name = "ReadForge"
uuid = "70e21103-1aff-4cdc-b686-ca5c4c9b5291"
authors = ["Periareion <periareion05@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
